#!/usr/bin/env python3
import json

def make_q(qid, diff, qtype, prompt, opts, expl, bonus=None, lang=None, code=None):
    return {
        "id": qid,
        "themeId": "apache-kafka",
        "difficulty": diff,
        "type": qtype,
        "prompt": prompt,
        "codeSnippet": {"language": lang, "code": code} if code is not None else None,
        "options": [{"id": o[0], "text": o[1], "isCorrect": o[2]} for o in opts],
        "explanation": expl,
        "bonusFact": bonus
    }

def t(qid, prompt, opts, expl, bonus=None):
    d = "intermediate" if "int" in qid else "advanced"
    return make_q(qid, d, "text", prompt, opts, expl, bonus)

def c(qid, prompt, lang, code, opts, expl, bonus=None):
    d = "intermediate" if "int" in qid else "advanced"
    return make_q(qid, d, "code-snippet", prompt, opts, expl, bonus, lang, code)

intermediate = [

t("apache-kafka-int-001",
 "When a producer uses acks=all and a topic has min.insync.replicas=2, what happens if only 1 replica is in-sync at write time?",
 [("a","The write is rejected with a NotEnoughReplicasException",True),
  ("b","The write succeeds because the leader replica is available",False),
  ("c","The write is queued until a second replica rejoins the ISR",False),
  ("d","The leader steps down and triggers a new partition leader election",False)],
 "With acks=all the broker requires at least min.insync.replicas replicas to acknowledge the write; with only 1 ISR member when min.insync.replicas=2 the broker immediately rejects with NotEnoughReplicasException. Option B is wrong because the ISR quorum requirement is not satisfied by the leader alone. Option C is incorrect because Kafka fails the request immediately rather than queuing it. Option D is wrong because ISR shrinkage does not trigger a leader election.",
 "Setting min.insync.replicas=2 with replication.factor=3 tolerates one broker failure safely."),

t("apache-kafka-int-002",
 "Which single producer configuration enables idempotent delivery in Kafka 4.x, preventing duplicate records on retry?",
 [("a","enable.idempotence=true",True),
  ("b","acks=all alone",False),
  ("c","retries=2147483647 alone",False),
  ("d","max.in.flight.requests.per.connection=1",False)],
 "enable.idempotence=true assigns the producer a unique Producer ID (PID) and per-partition sequence numbers that the broker uses to detect and discard duplicate batches on retry. acks=all (Option B) increases durability but does not prevent duplicates when a retry occurs without idempotent state. retries alone (Option C) causes duplicates because no deduplication mechanism exists. max.in.flight=1 (Option D) reduces reordering risk but still permits duplicate records without the PID/sequence mechanism.",
 "In Kafka 3.0+, enable.idempotence defaults to true when acks is not explicitly set to 0 or 1."),

t("apache-kafka-int-003",
 "What is the primary advantage of the cooperative (incremental) rebalance protocol over the eager rebalance protocol?",
 [("a","Cooperative rebalancing revokes only partitions that must move, avoiding a full stop-the-world processing pause",True),
  ("b","Cooperative rebalancing revokes all partitions before reassignment, just like eager rebalancing",False),
  ("c","Cooperative rebalancing is only available with the RoundRobinAssignor strategy",False),
  ("d","Cooperative rebalancing requires ZooKeeper coordination and is unavailable in KRaft mode",False)],
 "The cooperative protocol (KIP-429) revokes only the subset of partitions that must change owners, allowing consumers to continue processing all remaining partitions without interruption during the rebalance. The eager protocol (Option B) revokes all partitions from every consumer before any reassignment, creating a full processing pause. Option C is wrong—CooperativeStickyAssignor is the strategy implementing this protocol. Option D is wrong—ZooKeeper is absent in Kafka 4.x and cooperative rebalancing works via the broker group coordinator.",
 "CooperativeStickyAssignor combines incremental rebalancing with sticky assignments for minimal disruption."),

t("apache-kafka-int-004",
 "In Kafka 4.x KRaft mode, which internal component stores the cluster metadata previously managed by ZooKeeper?",
 [("a","The __cluster_metadata internal log replicated by the KRaft controller quorum",True),
  ("b","The __consumer_offsets internal topic on the broker with the most partitions",False),
  ("c","A ZooKeeper ensemble that must still be present alongside the KRaft controllers",False),
  ("d","Each broker's local log directory independently with no central coordination",False)],
 "In KRaft mode all cluster metadata—broker registrations, topic configs, partition assignments, and ISR changes—is stored in the __cluster_metadata log replicated across the KRaft controller quorum via Raft consensus. Option B (__consumer_offsets) stores consumer group committed offsets, not cluster topology. Option C is wrong because Kafka 4.0 removed ZooKeeper entirely. Option D is wrong because metadata is centrally managed by the quorum, not independently per broker.",
 "Kafka 4.0 dropped ZooKeeper; KRaft became the only metadata management system."),

t("apache-kafka-int-005",
 "What triggers the Kafka log cleaner to run compaction on a partition?",
 [("a","The ratio of dirty (uncompacted) bytes to total log bytes exceeds log.cleaner.min.dirty.ratio",True),
  ("b","The number of messages exceeds the log.retention.ms threshold",False),
  ("c","The active log segment reaches its maximum configured byte size",False),
  ("d","A consumer explicitly requests compaction through the AdminClient API",False)],
 "The log cleaner selects partitions when the dirty ratio (uncompacted bytes / total bytes) exceeds log.cleaner.min.dirty.ratio (default 0.5). Option B confuses time-based retention deletion with compaction—they are separate cleanup mechanisms. Option C is related (rolling creates closed segments eligible for compaction) but the cleaner never compacts the active segment regardless. Option D is wrong—compaction is entirely broker-driven and cannot be externally triggered.",
 "The active segment is never compacted regardless of its dirty ratio."),

t("apache-kafka-int-006",
 "When both log.retention.ms and log.retention.bytes are configured on a topic, how does Kafka decide when to delete segments?",
 [("a","Both limits are enforced independently; a segment is deleted when either threshold is exceeded first",True),
  ("b","log.retention.ms always takes precedence over log.retention.bytes",False),
  ("c","log.retention.bytes always takes precedence over log.retention.ms",False),
  ("d","Configuring both simultaneously causes a broker startup error",False)],
 "Kafka evaluates both retention conditions concurrently; a segment is eligible for deletion if it is older than log.retention.ms OR if total log size exceeds log.retention.bytes—whichever triggers first. Option B is wrong because both conditions are evaluated independently. Option C is wrong for the same reason. Option D is incorrect—both settings are valid together and commonly combined in production.",
 None),

t("apache-kafka-int-007",
 "What is the fundamental difference between a Kafka Connect source connector and a sink connector?",
 [("a","Source connectors read from external systems and write to Kafka; sink connectors read from Kafka and write to external systems",True),
  ("b","Source connectors handle schema evolution; sink connectors only handle data serialization",False),
  ("c","Source connectors are stateless; sink connectors maintain all state in __consumer_offsets",False),
  ("d","Source connectors require a Schema Registry; sink connectors work without any schema validation",False)],
 "Source connectors ingest data from external systems (databases, files, queues) into Kafka topics, while sink connectors consume from Kafka topics and deliver data to external targets (data warehouses, search indexes, NoSQL stores). Option B is wrong—both types can handle schema evolution independently. Option C is wrong—source connectors also maintain state stored in Kafka internal topics. Option D is wrong—neither type mandatorily requires a Schema Registry.",
 "Confluent's JDBC Source Connector uses incrementing, timestamp, or bulk modes for database ingestion."),

t("apache-kafka-int-008",
 "What does the consumer lag metric represent for a Kafka consumer group partition?",
 [("a","The difference between the partition log end offset and the group committed offset, representing unconsumed messages",True),
  ("b","The network round-trip latency in milliseconds between the consumer and the broker",False),
  ("c","The number of consumers in the group currently in the rebalancing state",False),
  ("d","The number of messages per second the consumer is failing to process",False)],
 "Consumer lag equals log_end_offset minus committed_offset per partition, representing the count of produced-but-not-yet-consumed messages. Option B describes network latency, which is a separate operational concern unrelated to consumer lag. Option C describes a transient consumer group coordination state, not a message count. Option D describes throughput deficit, which is a consequence of sustained lag but not its definition.",
 "kafka-consumer-groups.sh --describe and JMX expose per-partition lag and LOG-END-OFFSET values."),

t("apache-kafka-int-009",
 "Which producer-side configuration combination is required to achieve exactly-once semantics end-to-end in Kafka?",
 [("a","enable.idempotence=true plus a transactional.id configured on the producer",True),
  ("b","acks=all and min.insync.replicas=2 alone without idempotence",False),
  ("c","enable.idempotence=true combined with acks=0 for maximum throughput",False),
  ("d","retries=0 combined with enable.idempotence=true",False)],
 "End-to-end EOS requires an idempotent producer (enable.idempotence=true) to prevent duplicates on retry, plus a transactional.id to enable atomic multi-partition writes and allow consumers to use isolation.level=read_committed. Option B provides durability but retries can still produce duplicates without idempotent state. Option C is invalid—acks=0 means no acknowledgment, making idempotence meaningless. Option D (retries=0) causes at-most-once semantics.",
 "Kafka Streams enables EOS by setting processing.guarantee=exactly_once_v2."),

t("apache-kafka-int-010",
 "How does Kafka determine which broker acts as the transaction coordinator for a given producer?",
 [("a","The transactional.id is hashed to a partition of __transaction_state; that partition's leader is the coordinator",True),
  ("b","The KRaft controller always acts as the transaction coordinator for all producers",False),
  ("c","The broker with the most available heap memory is dynamically chosen as coordinator",False),
  ("d","Transaction coordination is handled externally by the Schema Registry service",False)],
 "Kafka hashes the transactional.id to a partition of __transaction_state (default 50 partitions); the leader of that partition serves as the transaction coordinator. Option B is wrong—the KRaft controller manages cluster metadata and elections, not transaction state. Option C is wrong—coordinator assignment is deterministic via hashing, not load-based. Option D is wrong—Schema Registry handles schema metadata, not Kafka transactions.",
 None),

t("apache-kafka-int-011",
 "What is the semantic difference between a KStream and a KTable in Kafka Streams?",
 [("a","KStream models each record as an independent event; KTable models the latest value per key as an updatable materialized view",True),
  ("b","KStream is backed by a RocksDB state store; KTable is stateless and holds no local data",False),
  ("c","KStream supports only windowed aggregations; KTable handles only non-windowed counts",False),
  ("d","KStream reads from regular retention topics only; KTable reads from compacted topics only",False)],
 "A KStream represents an append-only event log where each record is independent (like a stream of transactions). A KTable represents a materialized view where each new record for a key replaces the previous value (like a database table updated via upsert). Option B is backwards—KTable uses a state store backed by a changelog topic; KStream processes records statelessly per record. Option C is wrong—both support various aggregations. Option D is wrong—there is no strict coupling between stream/table types and topic cleanup policies.",
 "KTable changelog topics enable fault-tolerant state recovery after task failure or rebalance."),

t("apache-kafka-int-012",
 "What is the key difference between a tumbling window and a hopping window in Kafka Streams?",
 [("a","Tumbling windows are non-overlapping fixed-size intervals; hopping windows have a fixed size but advance by a smaller step causing overlap",True),
  ("b","Tumbling windows overlap; hopping windows are strictly non-overlapping",False),
  ("c","Tumbling windows use event time; hopping windows use wall-clock time exclusively",False),
  ("d","Tumbling windows are only in the Processor API; hopping windows are only in the DSL",False)],
 "A tumbling window divides time into consecutive non-overlapping fixed-size buckets so each record belongs to exactly one window. A hopping window has a size larger than its advance step (e.g. size=10min, step=1min), causing windows to overlap and each record to potentially appear in multiple windows. Option B reverses the descriptions. Option C is wrong—both use stream time by default in Kafka Streams. Option D is wrong—both types are supported in the DSL.",
 None),

t("apache-kafka-int-013",
 "In Confluent Schema Registry, what does BACKWARD compatibility mode guarantee for schema consumers?",
 [("a","Consumers using the new schema can read data written with the previous (older) schema version",True),
  ("b","Consumers using the old schema can read data written with any newer schema version",False),
  ("c","Any schema change including field removal is permitted without compatibility checks",False),
  ("d","Data written with the new schema can be read by all older schema versions",False)],
 "BACKWARD compatibility ensures that upgrading consumers (using the latest schema) can still deserialize records serialized by producers using the previous schema, enabling rolling consumer upgrades before producer upgrades. Option B describes FORWARD compatibility where older consumers can read newer data. Option C is wrong—BACKWARD disallows removing required fields. Option D describes FULL compatibility (bidirectional), which is stricter than BACKWARD alone.",
 "Adding a new optional field with a default value is the most common BACKWARD-compatible change."),

t("apache-kafka-int-014",
 "What is the maximum number of consumers in a single consumer group that can actively read from a topic with 8 partitions?",
 [("a","8 — one consumer per partition is the maximum active limit within a group",True),
  ("b","16 — two consumers can cooperatively share a single partition",False),
  ("c","Unlimited — Kafka supports any number of concurrent consumers per partition",False),
  ("d","4 — parallelism is capped at half the partition count by default",False)],
 "Kafka assigns each partition to at most one consumer within a group at any time, capping active parallelism at the partition count. Extra consumers beyond the partition count are assigned no partitions and sit idle waiting for failover. Option B is wrong—a single partition cannot be consumed by two consumers in the same group simultaneously. Option C is wrong for the same reason. Option D has no basis in Kafka's assignment logic.",
 "Idle excess consumers act as hot standbys, ready to take over when an active consumer fails."),

t("apache-kafka-int-015",
 "When is ConsumerRebalanceListener.onPartitionsRevoked() called during an eager rebalance?",
 [("a","Before the consumer loses its current partition assignments, giving it time to commit offsets and clean up state",True),
  ("b","After new partitions have already been assigned to other consumers in the group",False),
  ("c","Only when the consumer calls unsubscribe() explicitly, not during coordinator-triggered rebalances",False),
  ("d","After the framework automatically commits all pending offsets on the consumer's behalf",False)],
 "During an eager rebalance, onPartitionsRevoked() fires before the current assignments are revoked, giving the application a window to call commitSync() and clean up partition-specific state for a clean handoff. Option B is wrong—it fires before reassignment, not after new assignments are made. Option C is wrong—it is triggered by all rebalance types including coordinator-initiated ones. Option D is wrong—Kafka does not auto-commit at this moment; the application must do so explicitly.",
 None),

t("apache-kafka-int-016",
 "What is the primary risk of using enable.auto.commit=true in a Kafka consumer without additional safeguards?",
 [("a","Offsets may be committed before records are fully processed, causing silent message loss on consumer restart",True),
  ("b","The consumer never commits offsets, causing all records to be reprocessed after every restart",False),
  ("c","Auto-commit requires the producer side to use acks=all on the same topics",False),
  ("d","Auto-commit disables exactly-once semantics only when reading from compacted topics",False)],
 "With auto-commit, offsets are periodically committed (every auto.commit.interval.ms) regardless of whether the application has finished processing those records. If the consumer crashes after the commit fires but before processing completes, those records are silently skipped on restart. Option B is the opposite—auto-commit fires automatically on a timer. Option C is wrong—auto-commit is purely a consumer-side concern. Option D is wrong—auto-commit undermines EOS for all topic types.",
 "Use commitSync() after processing each batch for reliable at-least-once delivery guarantees."),

t("apache-kafka-int-017",
 "Which Kafka compression codec provides the best combination of compression ratio and speed for most production workloads?",
 [("a","zstd (Zstandard)",True),
  ("b","gzip",False),
  ("c","snappy",False),
  ("d","lz4",False)],
 "zstd (Zstandard, available since Kafka 2.1) delivers superior compression ratios compared to snappy and lz4 while maintaining competitive decompression speeds, making it the best general-purpose codec. gzip (Option B) achieves good ratios but is the slowest codec and increases CPU overhead significantly. snappy (Option C) is faster than gzip but provides lower compression ratios than zstd. lz4 (Option D) prioritizes speed over ratio, ideal for latency-sensitive pipelines.",
 "Kafka compresses entire batches; larger batches improve effective compression ratios significantly."),

t("apache-kafka-int-018",
 "How does reducing log.segment.bytes affect log compaction behavior on a Kafka partition?",
 [("a","Smaller segments roll to closed state more frequently, giving the log cleaner more segments to compact sooner",True),
  ("b","Smaller segments disable log compaction entirely for that partition",False),
  ("c","Smaller segments automatically reduce log.retention.ms thresholds proportionally",False),
  ("d","Smaller segments prevent the active segment from accepting new message writes",False)],
 "When log.segment.bytes is smaller, the active segment fills and rolls to a closed (immutable) segment more quickly; closed segments are eligible for compaction, so more frequent rolling means the log cleaner encounters more compaction candidates sooner. Option B is wrong—segment size has no effect on whether compaction is enabled. Option C is wrong—retention settings are independent configurations. Option D is wrong—the active segment always accepts writes until its size limit is reached.",
 None),

t("apache-kafka-int-019",
 "When a consumer sets fetch.min.bytes=65536 and the broker has fewer bytes available, what does the broker do?",
 [("a","The broker waits up to fetch.max.wait.ms before responding with whatever data is available at that point",True),
  ("b","The broker immediately returns an empty fetch response to prevent consumer starvation",False),
  ("c","The consumer retries the fetch request in a tight loop until the threshold is satisfied",False),
  ("d","The fetch request is rejected and the consumer is forced to rejoin the consumer group",False)],
 "When available data is below fetch.min.bytes the broker holds the fetch request open (a long-poll) for up to fetch.max.wait.ms, accumulating new records before responding; this reduces fetch overhead on low-throughput partitions. Option B is wrong—the broker waits rather than responding immediately with an empty result. Option C is wrong—the consumer is blocked awaiting the broker's held response. Option D is wrong—fetch threshold mismatches cause no rejections or rebalances.",
 "Increasing fetch.min.bytes reduces broker CPU overhead but increases end-to-end consumer latency."),

t("apache-kafka-int-020",
 "What is the behavioral difference between batch.size and linger.ms in Kafka producer configuration?",
 [("a","batch.size is the maximum byte size of a batch; linger.ms is the maximum time the producer waits to fill a batch before sending",True),
  ("b","batch.size controls the number of records per batch; linger.ms controls partitions batched together",False),
  ("c","linger.ms only applies when acks=all; batch.size applies regardless of the acks setting",False),
  ("d","Both control the same accumulation threshold and are mutually exclusive settings",False)],
 "batch.size sets the upper byte limit for a single batch; the producer sends when batch.size is reached OR linger.ms expires, whichever comes first. linger.ms artificially delays sending to accumulate more records, improving compression and throughput. Option B is wrong—batch.size is in bytes, not record count. Option C is wrong—linger.ms applies regardless of acks. Option D is wrong—they are complementary settings that work together.",
 "Setting linger.ms=5-20ms can significantly improve throughput with minimal latency impact."),

t("apache-kafka-int-021",
 "What happens when kafka-topics.sh --delete is run on a topic with delete.topic.enable=true?",
 [("a","The topic is marked for deletion and brokers asynchronously remove log segment data in the background",True),
  ("b","The topic is immediately and synchronously deleted with all consumers notified in real time",False),
  ("c","The topic data is retained but all new produce requests to it are rejected immediately",False),
  ("d","Deletion is only allowed when the topic has zero active consumer group members",False)],
 "With delete.topic.enable=true (the default), the controller marks the topic as deleted in cluster metadata; brokers then asynchronously clean up log segments in the background. Producers and consumers may briefly still interact with the topic during cleanup. Option B is wrong—deletion is asynchronous, not synchronous. Option C does not describe Kafka's actual deletion behavior. Option D is wrong—Kafka does not check for active consumers before allowing deletion.",
 None),

t("apache-kafka-int-022",
 "Which ACL configuration correctly grants a principal permission to produce messages to a Kafka topic?",
 [("a","Resource type TOPIC, operation WRITE, on the specific topic name",True),
  ("b","Resource type CLUSTER, operation WRITE",False),
  ("c","Resource type TOPIC, operation CREATE",False),
  ("d","Resource type GROUP, operation WRITE",False)],
 "Producing to a topic requires the WRITE operation on the TOPIC resource type scoped to the target topic name; Kafka also typically requires DESCRIBE permission to fetch topic metadata. Option B (CLUSTER, WRITE) grants cluster-level operations like creating ACLs or modifying broker configs. Option C (TOPIC, CREATE) allows creating new topics, not producing to existing ones. Option D (GROUP, WRITE) does not map to a produce permission in Kafka's ACL model.",
 "Kafka producers also need the DESCRIBE ACL on a topic to successfully fetch its partition metadata."),

t("apache-kafka-int-023",
 "Which SASL authentication mechanism in Kafka uses Kerberos tickets for mutual authentication?",
 [("a","GSSAPI",True),
  ("b","PLAIN",False),
  ("c","SCRAM-SHA-256",False),
  ("d","OAUTHBEARER",False)],
 "GSSAPI (Generic Security Services API) is the SASL mechanism that leverages Kerberos for mutual authentication between clients and brokers, widely used in enterprise Hadoop environments. PLAIN (Option B) sends credentials in cleartext and relies on TLS for security, without Kerberos. SCRAM-SHA-256 (Option C) uses salted challenge-response with stored password verifiers, not Kerberos tickets. OAUTHBEARER (Option D) integrates with OAuth 2.0 token-based systems.",
 "SCRAM-SHA-512 is preferred over PLAIN for non-Kerberos deployments needing stronger security."),

t("apache-kafka-int-024",
 "In Kafka TLS configuration, what is the functional difference between ssl.keystore.location and ssl.truststore.location?",
 [("a","The keystore holds the entity's own certificate and private key; the truststore holds trusted CA certificates for verifying peers",True),
  ("b","The keystore stores trusted CA certificates; the truststore stores the entity's private key",False),
  ("c","Both stores hold identical CA certificates duplicated for redundancy",False),
  ("d","The truststore is only needed for mutual TLS; the keystore is always required for one-way TLS",False)],
 "The keystore contains the entity's own identity—its certificate and private key—presented to the peer during TLS handshake to prove its identity. The truststore contains trusted Certificate Authority certificates used to validate the peer's certificate during handshake. Option B reverses their roles completely. Option C is wrong—they hold different data serving distinct purposes. Option D is partially accurate for mTLS but the broader claim is context-dependent.",
 None),

t("apache-kafka-int-025",
 "What key advantages does MirrorMaker 2 (MM2) provide over the original MirrorMaker 1?",
 [("a","MM2 supports active-active replication, automatic offset translation, and consumer group offset synchronization between clusters",True),
  ("b","MM2 is a lightweight standalone daemon that does not rely on Kafka Connect internally",False),
  ("c","MM2 eliminates the need for dedicated consumer groups on the source cluster",False),
  ("d","MM2 replicates ZooKeeper metadata alongside Kafka topic data for complete cluster mirroring",False)],
 "MirrorMaker 2, built on Kafka Connect, adds bidirectional active-active replication support, automatic source-to-target offset mapping allowing consumers to resume on the target cluster, heartbeat topics for replication monitoring, and consumer group offset synchronization. Option B is wrong—MM2 is explicitly built on the Kafka Connect framework. Option C is wrong—MM2 still uses consumer groups on the source cluster. Option D is wrong—ZooKeeper is removed in Kafka 4.x.",
 "MM2 creates mm2-heartbeats and mm2-offsets topics to monitor and translate replication state."),

t("apache-kafka-int-026",
 "What is the primary use case for Kafka record headers?",
 [("a","Attaching metadata such as trace IDs, correlation IDs, or source system tags to records without modifying the message payload",True),
  ("b","Routing records to specific partitions by overriding the partitioner based on header values",False),
  ("c","Storing schema version information as a drop-in replacement for the Schema Registry",False),
  ("d","Compressing individual records independently of batch-level compression settings",False)],
 "Record headers provide lightweight key-value metadata for cross-cutting concerns like distributed tracing (injecting OpenTelemetry trace IDs), audit logging, or source system identification without touching the business payload. Option B is wrong—partition routing is determined by the record key and partitioner, not headers. Option C is wrong—while headers can technically carry schema IDs, the standard approach embeds schema ID in the payload prefix. Option D is wrong—headers do not affect compression.",
 None),

t("apache-kafka-int-027",
 "When log.cleanup.policy is set to 'compact,delete' on a Kafka topic, what behavior results?",
 [("a","Both policies run simultaneously: compaction retains the latest value per key while retention-based deletion removes old segments",True),
  ("b","The topic alternates between compaction mode and deletion mode on successive cleanup cycles",False),
  ("c","Compaction completes first; once finished, deletion permanently disables further compaction",False),
  ("d","Deletion removes all records immediately; compaction is never triggered with this combined policy",False)],
 "With compact,delete Kafka applies both cleanup policies concurrently in each cycle: the log cleaner compacts segments to keep the latest value per key while the log manager deletes segments exceeding time or size retention limits. Option B is wrong—both operate concurrently, not alternately. Option C is wrong—deletion does not disable compaction. Option D is wrong—deletion only targets segments beyond retention limits, not all records.",
 "compact,delete is useful for changelog topics that need deduplication AND bounded total size."),

t("apache-kafka-int-028",
 "What is the difference between a Kafka consumer's current position and its committed offset?",
 [("a","The current position is the next offset to fetch; the committed offset is the durable checkpoint stored in __consumer_offsets",True),
  ("b","They are always identical — Kafka synchronizes them automatically after every poll() call",False),
  ("c","The committed offset always leads the current position by exactly one record",False),
  ("d","The current position is stored in ZooKeeper; the committed offset is maintained in broker memory",False)],
 "The current position advances with each poll() call tracking the next offset to fetch, while the committed offset is explicitly persisted to __consumer_offsets and determines where the consumer resumes after restart. The gap between them represents records fetched but not yet committed. Option B is wrong—they diverge whenever records are fetched but uncommitted. Option C is wrong—the current position typically leads the committed offset. Option D is wrong—ZooKeeper is removed in Kafka 4.x.",
 None),

t("apache-kafka-int-029",
 "How do follower replicas in Kafka replicate data from the partition leader?",
 [("a","Each follower runs a replica fetcher thread that sends FetchRequests to the leader, pulling ordered records in sequence",True),
  ("b","The leader pushes records to followers using a push-based streaming model",False),
  ("c","Followers replicate by reading the leader's log files directly through a shared file system mount",False),
  ("d","Replication is managed by the ZooKeeper ensemble in Kafka 4.x KRaft mode",False)],
 "Follower replicas maintain a dedicated replica fetcher thread per leader-broker pair that issues FetchRequests (the same protocol used by consumers) to pull ordered records from the leader's partition log. Option B is wrong—Kafka uses a pull model for replication, not push. Option C is wrong—replication uses the Kafka network protocol, not shared file systems. Option D is wrong—ZooKeeper is absent in Kafka 4.x and was never involved in data replication.",
 "The num.replica.fetchers broker config controls how many fetcher threads run per broker."),

t("apache-kafka-int-030",
 "Under what condition is a follower replica removed from the In-Sync Replica (ISR) set?",
 [("a","The follower fails to fetch from the leader within replica.lag.time.max.ms, indicating it is falling behind",True),
  ("b","The follower's disk utilization exceeds 80% of its total configured storage capacity",False),
  ("c","The follower begins serving consumer read requests during a period of leader unavailability",False),
  ("d","The follower's network throughput drops below a minimum bytes-per-second threshold",False)],
 "A follower is evicted from the ISR when it fails to issue a FetchRequest to the leader within replica.lag.time.max.ms (default 30 seconds), indicating it can no longer guarantee it holds all committed messages. Option B is wrong—disk utilization is not part of ISR tracking logic. Option C is wrong—followers don't serve consumer reads normally and doing so would not cause ISR removal. Option D is wrong—there is no bytes-per-second threshold for ISR membership.",
 "A follower automatically re-joins the ISR once it fully catches up to the leader's log end offset."),

t("apache-kafka-int-031",
 "What role does RocksDB play in a Kafka Streams application?",
 [("a","RocksDB is the default embedded persistent key-value state store used for stateful operations like aggregations and joins",True),
  ("b","RocksDB stores consumer group committed offsets for all Kafka Streams tasks",False),
  ("c","RocksDB handles inter-instance network communication between distributed Streams instances",False),
  ("d","RocksDB caches broker log segments locally on Streams worker nodes to reduce network I/O",False)],
 "Kafka Streams embeds RocksDB as its local persistent store for stateful operations (windowed aggregations, KTable materialization, joins), enabling state that exceeds heap memory by spilling to local disk with state backed by Kafka changelog topics for fault tolerance. Option B is wrong—consumer offsets are tracked in __consumer_offsets on the broker, not RocksDB. Option C is wrong—Streams instances communicate via Kafka topics. Option D is wrong—RocksDB is on the application node, not the broker.",
 "RocksDB state stores are backed by changelog topics enabling recovery without reprocessing source data."),

t("apache-kafka-int-032",
 "What distinguishes a GlobalKTable from a regular KTable in Kafka Streams?",
 [("a","GlobalKTable is fully replicated to all Streams instances; KTable is partitioned and each instance holds only its assigned partitions",True),
  ("b","GlobalKTable supports windowed joins; KTable does not support time-based join operations",False),
  ("c","GlobalKTable reads from regular retention topics; KTable reads exclusively from compacted topics",False),
  ("d","GlobalKTable requires co-partitioning with joined streams; KTable relaxes this requirement",False)],
 "A GlobalKTable broadcasts all records to every Streams application instance regardless of partition assignment, making it ideal for small lookup tables that need to be joinable with any partition without co-partitioning. A regular KTable is partitioned—each instance holds only the state for its assigned partitions and must be co-partitioned with joined streams. Option B is wrong—windowed joins involve KStream-KStream operations. Option C is wrong—both can read from various topic types. Option D reverses the actual requirement.",
 "GlobalKTable is ideal for small reference datasets like product catalogs that join with any partition."),

t("apache-kafka-int-033",
 "Which Kafka Connect Single Message Transform (SMT) extracts a single named field from a Struct record and replaces the entire record with that field's value?",
 [("a","ExtractField",True),
  ("b","ReplaceField",False),
  ("c","HoistField",False),
  ("d","Flatten",False)],
 "ExtractField pulls a named field out of a Struct or Map record and replaces the entire record with just that extracted value, useful for unwrapping nested envelopes such as Debezium CDC events. ReplaceField (Option B) includes or excludes named fields while keeping the outer Struct structure intact. HoistField (Option C) does the inverse—wraps a scalar value into a new Struct with a given field name. Flatten (Option D) collapses nested Structs into a single-level Struct.",
 None),

t("apache-kafka-int-034",
 "What happens to records that fail processing in a Kafka Connect sink connector when a dead letter queue (DLQ) is configured?",
 [("a","Failed records are published to the DLQ Kafka topic with error context stored in record headers for offline inspection",True),
  ("b","Failed records cause the connector task to pause until an operator manually restarts it",False),
  ("c","Failed records are silently discarded and the connector continues without any error notification",False),
  ("d","Failed records are replayed automatically from the beginning of the source topic",False)],
 "When errors.deadletterqueue.topic.name is configured, records failing serialization, transformation, or delivery are forwarded to the DLQ topic with error context (original topic, partition, offset, exception message, stack trace) embedded in record headers. Option B describes the behavior when errors.tolerance=none without a DLQ—the task fails and pauses. Option C describes errors.tolerance=all without a DLQ—failures are silently dropped. Option D is wrong—Kafka Connect does not replay from topic beginning.",
 "DLQ record headers include the original topic, partition, offset, and full exception stack trace."),

t("apache-kafka-int-035",
 "What is the primary operational benefit of enabling tiered storage in Apache Kafka 4.x?",
 [("a","Local broker disk usage is reduced by offloading older log segments to remote object storage while keeping recent data locally",True),
  ("b","Tiered storage recompresses all data to zstd format before uploading to the remote tier",False),
  ("c","Tiered storage eliminates the need for partition replication by storing data redundantly in object storage",False),
  ("d","Tiered storage enables consumers to achieve lower read latency than reading from local broker disk",False)],
 "Tiered storage (KIP-405, production-stable since Kafka 3.6) decouples retention from disk capacity by moving older segments to object storage (S3, GCS, Azure Blob), enabling much longer retention without scaling broker disk. Option B is wrong—tiered storage moves existing segments without changing their format. Option C is wrong—replication is still required for fault tolerance; tiered storage is an additional retention tier. Option D is wrong—remote fetch adds latency compared to local disk reads.",
 "Tiered storage is production-stable in Kafka 3.6+ and fully supported in Kafka 4.x."),

